package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u231/13620/corba/src/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Saturday, October 5, 2019 3:17:54 AM PDT
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
     * Constant, defined in the Messaging spec, to define how far the 
     * request shall progress before control is returned to the client.
     */
  public static final short value = (short)(1);
}
