server:
  port: 8000
spring:
  application:
    name: springcloud-alibaba-provider
  cloud:
    nacos:
      discovery:
        service: springcloud-alibaba-provider
      server-addr: 82.156.216.48:8848
dubbo:
  application:
    name: springcloud-alibaba-provider
    id: springcloud-alibaba-provider
  registry:
    # 注册中心地址
    address: nacos://82.156.216.48:8848/
  protocol:
    # 传输协议
    name: dubbo
    # 随机端口
    port: 20881
