spring:
  application:
    name: source-data
  datasource:
    url: jdbc:mysql://localhost:3306/source_data
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

server:
  port: 20000


