spring:
  application:
    name: spring-ai-llm
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        completions-path: ${COMPLETIONS_PATH}
        options:
          model: ${MODEL}
