spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        completions-path: ${COMPLETIONS_PATH}
        options:
          model: ${MODEL}
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client-sse
        type: ASYNC
        sse:
          connections:
            my-mcp-server:
              url: http://localhost:9060
              sse-endpoint: /sse
            amap-mcp-server:
              url: https://mcp.amap.com
              sse-endpoint: /sse?key=083de0464b2f8fd5127a34fb668c0477
